# Generated by Django 4.1.3 on 2022-12-12 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=35, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=35, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35, unique=True, verbose_name='Nombre de usuario')),
                ('nombreApellido', models.CharField(max_length=70, verbose_name='Nombre y Apellido')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('perfilImage', models.ImageField(blank=True, default='usuarios/default.png', null=True, upload_to='usuarios/', verbose_name='Foto de perfil')),
                ('rol', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticia.rol', verbose_name='Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitulo')),
                ('fechaCreacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('contenido', models.TextField(null=True, verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, default='noticia/default.png', null=True, upload_to='noticia/', verbose_name='Imagen')),
                ('fechaPublicacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Publicacion')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticia.persona', verbose_name='Autor')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticia.categoria', verbose_name='Categoría')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticia.status', verbose_name='Estado')),
            ],
            options={
                'ordering': ('-fechaPublicacion',),
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('contenido', models.CharField(max_length=50, verbose_name='Título')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticia.persona', verbose_name='Autor')),
                ('noticia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='noticia.noticia', verbose_name='Noticia')),
            ],
        ),
    ]
