# Generated by Django 4.1.3 on 2022-12-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, null=True),
        ),
    ]
