# Generated by Django 4.1.3 on 2022-12-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0005_alter_noticia_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.IntegerField(choices=[[0, 'Personal'], [1, 'Visitante'], [2, 'Admin'], [3, 'Autor']], default=1),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
