# Generated by Django 4.1.4 on 2022-12-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0006_alter_persona_rol_delete_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ('-rol',)},
        ),
    ]
